Vidly/Controllers/EspecieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewsModels;

namespace Vidly.Controllers
{
    public class EspecieController : Controller
    {
        //
        // GET: /Especie/
        private ApplicationDbContext _context;
        public EspecieController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public ActionResult Index()
        {
            var especie = _context.Especie.ToList();
            if (User.IsInRole("CanManageCustomers")) 
                return View(especie);
 
            return View("ReadOnlyIndex", especie);
        }
        public ActionResult Details(int Id)
        {
            var especies = _context.Especie.SingleOrDefault(c => c.id == Id);


            if (especies == null)
                return HttpNotFound();

            return View(especies);
        }
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Edit(int id)
        {
            var especie = _context.Especie.SingleOrDefault(c => c.id == id);

            if (especie == null)
                return HttpNotFound();

            var viewModel = new EspecieFormViewModels
            {
                Especie = especie

            };
            
            return View("EspecieForm", viewModel);
        }
        [HttpPost]
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Save(Species especie)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new EspecieFormViewModels
                {
                    Especie = especie
                };

                return View("EspecieForm", viewModel);
            }
         
            if (especie.id == 0)
            {
                _context.Especie.Add(especie);
            }
            else
            {
                var especieInDb = _context.Especie.Single(c => c.id == especie.id);

                especieInDb.nome = especie.nome;
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult New()
        {

            var viewModel = new EspecieFormViewModels
            {
                Especie = new Species()
            };

            return View("EspecieForm", viewModel);
        }
        [Authorize(Roles = "CanManageCustomers")]
         public ActionResult Delete(int id)
        {
            var especie = _context.Especie.SingleOrDefault(c => c.id == id);

            if (especie == null)
                return HttpNotFound();

            _context.Especie.Remove(especie);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
       
	}
}

Vidly/Views/Especie/Details.cshtml
@model Vidly.Models.Species
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Dados especie</h2>
<hr />

<ul>
    <li>Id: @Model.id</li>
    <li>Tipo: @Model.nome</li>
</ul>

Vidly/Views/Especie/EspecieForm.cshtml
@model Vidly.ViewsModels.EspecieFormViewModels
@{
    ViewBag.Title = Model.Title;
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Especie"))
{   
    
     @Html.HiddenFor(m => m.Especie.id)

    <div class="form-group">
        @Html.LabelFor(m => m.Especie.nome)
        @Html.TextBoxFor(m => m.Especie.nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Especie.nome)
    </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
}

  

Vidly/Views/Especie/Index.cshtml
@model IEnumerable<Vidly.Models.Species>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Espécies</h2></center>

@if (@Model.Any())
{
    <table  class=" table table-bordered table-hover" >
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Editar</th>
                <th>Remover</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var especie in Model)
{
    <tr>
        <td width="5px"><a href="/Especie/Details/@especie.id">@especie.id</a></td>
        <td width="5px">@Html.ActionLink(@especie.nome, "Details", new { especie.id })</td>
        <td width="5px"><a href="/Especie/edit/@especie.id"><input type="button" value="Editar"></a></td>
        <td width="5px"><a href="/Especie/delete/@especie.id"><input type="button" value="Remover"></a></td>
    </tr>   
}
        </tbody>
    </table>
}
else
{
    <p>Não possui nenhuma espécie cadastrada.</p>
}
@Html.ActionLink("Nova especie", "New", null, new { @class = "btn btn-primary" })

Vidly/Views/Especie/ReadOnlyIndex.cshtml
@model IEnumerable<Vidly.Models.Species>
@{
    ViewBag.Title = "ReadOnlyIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Espécies</h2></center>

@if (@Model.Any())
{
    <table class=" table table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var especie in Model)
            {
                <tr>
                    <td width="5px">@especie.id</td>
                    <td width="5px">@especie.nome</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não possui nenhuma espécie cadastrada.</p>
}