Vidly/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using System.Data.Entity;
using Vidly.ViewsModels;

namespace Vidly.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext _context;

        public CustomerController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public ActionResult Index()
        {
            var customer = _context.Customers.ToList();
            if (User.IsInRole("CanManageCustomers"))
                return View(customer);

            return View("ReadOnlyIndex", customer);
        }
        public ActionResult Details(int Id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.id == Id);


            if (customer == null)
                return HttpNotFound();

            return View(customer);
        }
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Edit(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.id == id);

            if (customer == null)
                return HttpNotFound();

            var viewModel = new CustomerFormViewModel
            {
                Customer = customer

            };

            return View("CustomerForm", viewModel);
        }
        [HttpPost]
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Save(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new CustomerFormViewModel
                {
                    Customer = customer
                };

                return View("CustomerForm", viewModel);
            }

            if (customer.id == 0)
            {
                _context.Customers.Add(customer);
            }
            else
            {
                var customerInDb = _context.Customers.Single(c => c.id == customer.id);

                customerInDb.nome = customer.nome;
                customerInDb.cpf = customer.cpf;
                customerInDb.endereco = customer.endereco;
                customerInDb.bairro = customer.bairro;
                customerInDb.num_casa = customer.num_casa;
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult New()
        {

            var viewModel = new CustomerFormViewModel
            {
                Customer = new Customer()
            };

            return View("CustomerForm", viewModel);
        }
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Delete(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.id == id);

            if (customer == null)
                return HttpNotFound();

            _context.Customers.Remove(customer);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
       
	}
}

Vidly/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using System.Data.Entity;
using Vidly.ViewsModels;

namespace Vidly.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
         private ApplicationDbContext _context;

        public ProductController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public ActionResult Index()
        {
            var produto = _context.Produto.ToList();
            if (User.IsInRole("CanManageCustomers"))
                return View(produto);

            return View("ReadOnlyIndex", produto);
        }
        public ActionResult Details(int Id)
        {
            var produto = _context.Produto.SingleOrDefault(c => c.id == Id);


            if (produto == null)
                return HttpNotFound();

            return View(produto);
        }
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Edit(int id)
        {
            var produto = _context.Produto.SingleOrDefault(c => c.id == id);

            if (produto == null)
                return HttpNotFound();

            var viewModel = new ProdutoFormViewModel
            {
                Produto = produto
            };

            return View("ProductForm", viewModel);
        }
        [HttpPost]
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Save(Product produto)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new ProdutoFormViewModel
                {
                    Produto = produto
                };

                return View("ProductForm", viewModel);
            }

            if (produto.id == 0)
            {
                _context.Produto.Add(produto);
            }
            else
            {
                var produtoInDb = _context.Produto.Single(c => c.id == produto.id);

                produtoInDb.nome = produto.nome;
                produtoInDb.quant = produto.quant;
                produtoInDb.preco = produto.preco;
                produtoInDb.descricao = produto.descricao;
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult New()
        {
            var viewModel = new ProdutoFormViewModel
            {
                Produto = new Product()
            };

            return View("ProductForm", viewModel);
        }
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Delete(int id)
        {
            var produto = _context.Produto.SingleOrDefault(c => c.id == id);

            if (produto == null)
                return HttpNotFound();

            _context.Produto.Remove(produto);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        
	}
}

Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Clientes", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Pets", "Index", "Pets")</li>
                    <li>@Html.ActionLink("Especie", "Index", "Especie")</li>
                    <li>@Html.ActionLink("Produto", "Index", "Product")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <!--<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>-->
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>