Vidly/Models/Pet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vidly.Models
{
    public class Pet
    {
        public int id { set; get;}
        [Required]
        [StringLength(255)]
        [Display(Name = "Nome")]
        public string nome {set;get;}
        [Required]
        [StringLength(255)]
        [Display(Name = "Raça")]
        public string raca { set; get; }
        public string cor { set; get; }
        public Species Especie { get; set; }
        [Display(Name = "Especie")]
        public int EspecieId { get; set; }
        public Customer cliente { get; set; }
        [Display(Name = "Dono")]
        public int ClienteId { get; set; }
    }
}

Vidly/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewsModels;
using System.Data.Entity;

namespace Vidly.Controllers
{
    public class PetsController : Controller
    {
        private ApplicationDbContext _context;
        public PetsController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        public ActionResult Index()
        {
            var pets = _context.Pet.Include(c => c.cliente).Include(c => c.Especie).ToList();
            if (User.IsInRole("CanManageCustomers"))
                return View(pets);

            return View("ReadOnlyIndex", pets);
        }
        public ActionResult Details(int Id)
        {
            var pets = _context.Pet.Include(c => c.cliente).Include(c => c.Especie).SingleOrDefault(c => c.id == Id);;


            if (pets == null)
                return HttpNotFound();

            return View(pets);
        }
         [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Edit(int id)
        {
            var pet = _context.Pet.SingleOrDefault(c => c.id == id);

            if (pet == null)
                return HttpNotFound();

            var especie = _context.Especie.ToList();
            var cliente = _context.Customers.ToList();
            var viewModel = new PetFormViewModels
            {
                Pet = pet,
                Especie = especie,
                cliente = cliente
            };

            return View("PetForm", viewModel);
        }
        [HttpPost]
        [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Save(Pet pet)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new PetFormViewModels
                {
                    Pet = pet,
                    Especie = _context.Especie.ToList(),
                    cliente = _context.Customers.ToList()
                };

                return View("PetForm", viewModel);
            }
            
            if (pet.id == 0)
            {
                _context.Pet.Add(pet);
            }
            else
            {
                var petInDb = _context.Pet.Single(c => c.id == pet.id);

                petInDb.nome = pet.nome;
                petInDb.raca = pet.raca;
                petInDb.cor = pet.cor;
                petInDb.EspecieId = pet.EspecieId;
                petInDb.ClienteId = pet.ClienteId;
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
         [Authorize(Roles = "CanManageCustomers")]
        public ActionResult New()
        {
            var especie = _context.Especie.ToList();
            var cliente = _context.Customers.ToList();
            var viewModel = new PetFormViewModels
            {
                Pet = new Pet(),
                Especie = especie,
                cliente = cliente
            };

            return View("PetForm", viewModel);
        }
         [Authorize(Roles = "CanManageCustomers")]
        public ActionResult Delete(int id)
        {
            var pet = _context.Pet.SingleOrDefault(c => c.id == id);

            if (pet == null)
                return HttpNotFound();

            _context.Pet.Remove(pet);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        

        
    }
}

Vidly/Views/Pets/Details.cshtml
@model Vidly.Models.Pet
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Dados pet</h2>
<hr />

<ul>
    <li>Id: @Model.id</li>
    <li>Nome: @Model.nome</li>
    <li>Raça: @Model.raca</li>
    <li>Cor: @Model.cor</li>
    <li>Cliente: @Model.cliente.nome</li>
    <li>Especie: @Model.Especie.nome</li>
</ul>

Vidly/Views/Pets/Index.cshtml
@model IEnumerable<Vidly.Models.Pet>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Pets</h2></center>

@if (@Model.Any())
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Raca</th>
                <th>Cliente</th>
                <th>Especie</th>
                <th>Editar</th>
                <th>Remover</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pet in Model)
            {
                <tr>
                    <td><a href="/Pets/Details/@pet.id">@pet.id</a></td>
                    <td>@Html.ActionLink(@pet.nome, "Details", new { pet.id })</td>
                    <td>@pet.raca</td>
                    <td>@pet.cliente.nome</td>
                    <td>@pet.Especie.nome</td>
                    <td width="5px"><a href="/Pets/edit/@pet.id"><input type="button" value="Editar"></a></td>
                    <td width="5px"><a href="/Pets/delete/@pet.id"><input type="button" value="Remover"></a></td>
                </tr>
            }
        </tbody>
    </table> 
}
else
{
    <p>Não possui nenhum pet cadastrado.</p>
}
@Html.ActionLink("Novo pet", "New", null, new { @class = "btn btn-primary" })

Vidly/Views/Pets/PetForm.cshtml
@model Vidly.ViewsModels.PetFormViewModels
@{
    ViewBag.Title = Model.Title;
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Save", "Pets"))
{
  @Html.HiddenFor(m => m.Pet.id)

    <div class="form-group">
        @Html.LabelFor(m => m.Pet.nome)
        @Html.TextBoxFor(m => m.Pet.nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Pet.nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Pet.raca)
        @Html.TextBoxFor(m => m.Pet.raca, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Pet.raca)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Pet.cor)
        @Html.TextBoxFor(m => m.Pet.cor, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Pet.cor)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Pet.EspecieId)
        @Html.DropDownListFor(m => m.Pet.EspecieId, new SelectList(Model.Especie, "id", "nome"),"Escolha", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Pet.EspecieId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Pet.ClienteId)
        @Html.DropDownListFor(m => m.Pet.ClienteId, new SelectList(Model.cliente, "id", "nome"),"Escolha", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Pet.ClienteId)
    </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
}

Vidly/Views/Pets/ReadOnlyIndex.cshtml
@model IEnumerable<Vidly.Models.Pet>
@{
    ViewBag.Title = "ReadOnlyIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h2>Pets</h2></center>

@if (@Model.Any())
{
    <table class=" table table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Raca</th>
                <th>Cliente</th>
                <th>Especie</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pet in Model)
            {
                <tr>
                    <td>@pet.id</td>
                    <td>@pet.nome</td>
                    <td>@pet.raca</td>
                    <td>@pet.cliente.nome</td>
                    <td>@pet.Especie.nome</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não possui nenhuma espécie cadastrada.</p>
}